version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - '3308:3308'
    environment:
       MYSQL_DATABASE: 'django'
       MYSQL_USER: 'django'
       MYSQL_PASSWORD: 'django'
       MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_project
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db