# Generated by Django 3.1.1 on 2023-02-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
